
variable "docker_login_password" {
  type    = string
  default = ""
}

variable "docker_login_repo" {
  type    = string
  default = "nsandeepprotech"
}

variable "docker_login_username" {
  type    = string
  default = "nsandeepprotech"
}

variable "image_name" {
  type    = string
  default = "docker-powershell-linter"
}

variable "image_tag" {
  type    = string
  default = "0.1"
}

source "docker" "autogenerated_1" {
  changes = ["ENTRYPOINT [ \"pwsh\", \"-c\" ]"]
  commit  = "true"
  image   = "mcr.microsoft.com/powershell:alpine-3.12"
  pull    = "true"
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    script = "./shell_scripts/install_ansible.sh"
  }

  provisioner "ansible-local" {
    playbook_file = "./ansible_scripts/install_psslinter.yml"
  }

  post-processors {
    post-processor "docker-tag" {
      repository = "${var.docker_login_repo}/${var.image_name}"
      tag        = "${var.image_tag}"
    }
    post-processor "docker-push" {
      login          = "true"
      login_password = "${var.docker_login_password}"
      login_username = "${var.docker_login_username}"
    }
  }
}
